# General perpose settings
General:
  challengeCompletionAnnouncement: True
  showWelcomeMessageOnJoin: True
  language: ru
# If you have a database you want to store data in you should specify your setting here
Database:
  db: "lolkek2"
  table: "table"
  # Change isRemote value to True if you are using a remote SQLite database, not the local one.
  # fill in host/port and credentials as well.
  isRemote: False
  Remote:
    host: "host"
    port: "port"
    user: "user"
    password: "password"
Integrations:
  Discord:
    webhookUrl: Null